### PR TITLE
Refacto/modular mains

### LINKED ISSUE #81: functional and modular main.py
Update main.py that will give users a complete and stable playground to iterate on modules.

Given the remaining time they have, users are going to work on specific modules as groups.

Having a pre-written main will ensure each group can work on the same robot without overlapping over ones work.
Not having this main would lead to huge conflicts and the merged code would have to be opiniated anyway, giving the users the feeling they did not really work on the definitive product that would not look like the original code they wrote.
So giving structure to the project not only reduce overlaps, it also helps users focusing on what matters the most: features (which are actually modules).

**I'm open to proposals.** Just laying 1 way this could be achieved : we could follow the work @ThibaudM13 started, splitting the code in two states : prepare / loop. Each module could therefore have those 2 methods (prepare / loop) users could fill.

main.py 
```python
def prepare():
  prepare_microphone()
  prepare_camera()
  ...
  
def loop():
  loop_microphone()
  loop_camera()
  ...

prepare()
loop()
```

I'm not hundred percent confident it would work but it would be the easiest way to split it, and would fit nicely with our current events system.
We could have a robot.events variable in the Robot and each module could register a new event which would internally fill robot.events.

### PR DESCRIPTION
**Pull request by ThibaudM13**
### NEW
Can now get colors easily in main by using: `Couleur.VERT` (for green)

### CHANGES
Examples mains can, now, be edited only for wished parts: buttons, display, session management or even events...
- All parts are now split into 2 parts for each: **preparation** and **loop function**.
- Called in main functions, students **won't** need to **manage** themselves where to **call function**

### Comments
I have tried with and without function for preparation part, the **inconvenient** for **function use**:
- Uses too much spaces, makes code **less readable**
- Variables must be **initialized** as **None** + called as global for each function: makes **harder** to **maintain** and to **understand**
- **Students** have **difficulties** to **split** things in or out **functions**, **without** function, it makes **easier** to explain:
    - **before** & **out** of function scope: **preparation** part
    - **in** function: **verification**/ **display**
 
 On merge: should Close #81

### CODE REVIEW

**Comment by ThibaudM13** [comment]
Open to any comments/ improvement paths!
Should work with all features/ main examples, just need any approbation to apply this on all of them

**Comment by gpoblon** [comment]
So after further reading:

I more in favour of the v2 flavour.
I'd even suggest to split initialization single scope into multiple function (like you did for loops) and we'll call it a day, merge it and propose it to users.

**Comment by ThibaudM13** [comment]
Warning:
`exemple_chapter5.py` and `exemple_chapter6AI.py` are **NOT** updated to the new Robot main structure and use.
They are mixed up in the template main!
- Do we need to make simpler template main files, and update chapter 5 and 6 template
- Or we let the code as it is and delete template 5 and 6

Main template for now has this interface:
image

**Review by gpoblon — APPROVED** [review]
perfect

**Comment by gpoblon** [comment]
merged with #94 to solve conflicts and a bug

**Pull request closed without merging**
